A minor expansion of mygfa to compute node_steps
cucapra/pollen pull request #22
Opened 2023-02-16 03:14 UTC by anshumanmohan

mygfa.py now computes the NodeSteps<sub>s</sub> table described in https://github.com/cucapra/notes/blob/main/Pollen/relational.md#indexes. As Adrian suggests in the note, `odgi depth` is now a cinch. 

Just as a sanity check, here's a sketch of `k.gfa`.
![IMG_0041](https://user-images.githubusercontent.com/10830208/219258589-73e2ef26-a58d-40e3-82a3-4d926ad48f0b.jpg)

This produces the following node depth table, which I think is correct.
![Screen Shot 2023-02-15 at 7 12 04 PM](https://user-images.githubusercontent.com/10830208/219258661-4ff5b827-4dea-4486-87a4-46dcb62c57b3.png)

2023-02-18 01:09 UTC, sampsyo requested changes
Cool! Some Python-y suggestions within.

As one comment implies, it would be cool (not in this PR) to move these various processing commands to a different Python module from the data structures.

2023-02-18 01:09 UTC, sampsyo commented on mygfa.py
> +    def crush_n(self):
```suggestion
    def crush_n(self) -> "Segment":
```

To make it clear what this returns, (i.e., it doesn't mutate `self`).

2023-02-18 01:09 UTC, sampsyo commented on mygfa.py
> +            self.name,
Oops; thanks.

2023-02-18 01:09 UTC, sampsyo commented on mygfa.py
> +    def crush_n(self):
```suggestion
    def crush_n(self) -> "Graph":
```

Similarly.

2023-02-18 01:09 UTC, sampsyo commented on mygfa.py
> +            {name: Segment.crush_n(seg) for name, seg in self.segments.items()}
```suggestion
            {name: seg.crush_n() for name, seg in self.segments.items()}
```

2023-02-18 01:09 UTC, sampsyo commented on mygfa.py
> +    # https://github.com/cucapra/notes/blob/main/Pollen/relational.md#indexes
Probably no need for the hint about printing IMO.

2023-02-18 01:09 UTC, sampsyo commented on mygfa.py
> +    # node_depth(graph)
If it's OK, I would leave these out of the `__main__` thing. In a future phase, maybe we can move the commands to a different module where they have a proper CLI.

2023-02-18 01:09 UTC, sampsyo commented on mygfa.py
> +    for (segment, crossings) in node_steps(graph).items():
```suggestion
    for segment, crossings in node_steps(graph).items():
```

2023-02-24 20:11 UTC, anshumanmohan commented
This branch has a few more commits than the PR proposed, but I'm merging it and moving on. The additional commits are towards
- rudimentary testing (with diff instead of turnt)
- refactoring code into modules
- implementing `odgi degree`

2023-02-24 20:11 UTC, merged